#ABNF 1.0 UTF-8;
// contains czech variations of common colors based on HTML color names

language cs;
root $color_values;

public $color_values = (
	$red
	| $salmon
	| $dark_red
	| $pink
	| $magenta
	| $violet
	| $orange
	| $tan
	| $dark_orange
	| $ocre
	| $gold
	| $yellow
	| $light_yellow
	| $dark_yellow
	| $khaki
	| $peach
	| $purple
	| $dark_purple
	| $light_purple
	| $green
	| $light_green
	| $dark_green
	| $yellow_green
	| $lime
	| $olive
	| $blue_green
	| $azure
	| $blue
	| $light_blue
	| $dark_blue
	| $brown
	| $dark_brown
	| $light_brown
	| $white
	| $gray
	| $light_gray
	| $dark_gray
	| $black
	);

$dark = ($temný | $tmavě) {dark};
$temný = temn(ě|ou|á|é|ého|ém|ému|í|ý|ých|ým|ými) | tmavěí | nejtmavší;
$tmavý = tmav(ě|ou|á|é|ého|ém|ému|í|ý|ých|ým|ými) | tmavší | nejtmavší;

$light = $světlý {light};
$světlý = světl(e|ou|á|é|ého|ém|ému|í|ý|ých|ým|ými);

$dark_orange = ($dark $orange) {dark_orange} {#df6c00};
$dark_red = ($dark $red) {dark_red} {#8b0000};
$gold = (zlat(á|é|ého|ém|ému|ý|ých|ým|ými)) {gold} {#ffd700};
$magenta = (purpurov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {magenta} {#ff00ff};
$orange = (oranžov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {orange} {#ffa500};
$pink = (růžov(á|é|ě|ou|ý|ými|ých|ým)) {pink} {#ffc0cb};
$red = (červen(á|é|ou|ý|ých|ým|ými)) {red} {#ff0000};
$salmon = (lososov(á|é|ý|ou|ých|ými|ým)) {salmon} {#fa8072};
$tan = (pleťov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {tan} {#d2b48c};
$violet = (fialov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {violet} {#ee82ee};
$yellow = (žlut(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {yellow} {#ffff00};
$light_yellow = ($light $yellow) {light_yellow} {#ffffe0};
$khaki = (khaki) {khaki} {#bdb76b};
$peach = (broskvov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {peach} {#ffdab8};
$purple = (nachov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {purple} {#800080};
$dark_purple = ($dark $purple) {dark_purple} {#500050};
$light_purple = ($light $purple) {light_purple} {#b000b0};
$green = (zelen(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {green} {#009000};
$light_green = ($light $green) {light_green} {#a0eea0};
$dark_green = ($dark $green) {dark_green} {#005000};
$yellow_green = (žluto $green) {yellow_green} {#adff2f};
$lime = (limetkov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {lime} {#00ff00};
$olive = (olivov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {olive} {#808000};
$blue_green = (modro $green) {blue_green} {#66cdaa};
$azure = (azurov(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {azure} {#f0ffff};
$blue = (modr(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {blue} {#0000ff};
$light_blue = ($light $blue) {light_blue} {#87cefa};
$dark_blue = ($dark $blue) {dark_blue} {#00008b};
$brown = (hněd(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {brown} {#8b4513};
$dark_brown = ($dark $brown) {dark_brown} {#5b1500};
$light_brown = ($light $brown) {light_brown} {#f4a460};
$white = (bíl(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {white} {#ffffff};
$gray = (šediv(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými) | šed(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {gray} {#808080};
$light_gray = ($light $gray) {light_gray} {#d3d3d3};
$dark_gray = ($dark $gray) {dark_gray} {#303030};
$black = (čern(ou|á|é|ého|ém|ému|í|ý|ých|ým|ými)) {black} {#000000};
